const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const state = {page:'command', quotes:[], market:'all', services:[], geo:null, chat:[], busy:false, lastReply:'', capture:null, screenTimer:null, recorder:null, records:[], terminalBusy:false};
const pending = new Map();
const names = {command:'Command Center',trading:'Trading Cockpit',world:'Global War Room',markets:'Markets & Research',chat:'AI Chat & Voice',pc:'PC Control',mobile:'Mobile Control',camera:'Camera',comms:'Communications',memory:'Memory System',content:'Content Studio',agents:'Agents Manager',automation:'Automation',governance:'Governance',settings:'System & Settings'};
const native = {world:['World Monitor','http://127.0.0.1:3000/'],gods:['Gods Eye View','http://127.0.0.1:4173/'],mq3:['MQ3 cockpit','http://127.0.0.1:5050/'],mobile:['Jarvis mobile companion','http://127.0.0.1:8765/'],terminal:['Existing terminal studio','/terminal']};
const escape = x => String(x ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = (x,d=1)=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const currency = x=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString(undefined,{style:'currency',currency:'USD'}):'Unavailable';
const list = x=>Array.isArray(x)?x:[];
const icons = ()=>window.lucide?.createIcons();
function age(timestamp){const n=Date.parse(timestamp);if(!Number.isFinite(n))return 'time unknown';const s=Math.max(0,(Date.now()-n)/1000);return s<60?`${Math.floor(s)}s ago`:s<3600?`${Math.floor(s/60)}m ago`:s<86400?`${Math.floor(s/3600)}h ago`:`${Math.floor(s/86400)}d ago`;}
function url(raw){try{const u=new URL(raw);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
async function api(path, options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.timeout||18000);try{const response=await fetch(path,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers},signal:controller.signal,cache:'no-store'});let data;try{data=await response.json();}catch{throw Error(`Invalid service response (${response.status})`);}if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);return data;}finally{clearTimeout(timer);}}
async function once(key, task){if(pending.has(key))return pending.get(key);const p=task().finally(()=>pending.delete(key));pending.set(key,p);return p;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500);}
function record(text){state.records.unshift({time:new Date().toLocaleTimeString(),text});state.records=state.records.slice(0,14);$('#activity').innerHTML=state.records.map(x=>`<div class="activity-item"><small>${escape(x.time)} · THIS SESSION</small>${escape(x.text)}</div>`).join('');}
function setBadge(id,text,mode='') {const e=$(id);if(e){e.textContent=text;e.className='badge '+mode;}}
async function pc(){return once('pc',async()=>{try{const d=await api('/api/pc');if(d.error)throw Error('Hardware telemetry unavailable');const cpu=d.cpu_percent??d.cpu,ram=d.mem,gpu=d.gpu?.available===true?d.gpu.gpu_util_pct:null;$('#top-cpu').textContent=num(cpu)+'%';$('#top-ram').textContent=num(ram)+'%';$('#top-gpu').textContent=gpu===null?'N/A':num(gpu)+'%';$('#gauges').innerHTML=[['CPU',cpu],['RAM',ram],['GPU',gpu],['C: disk',d.disk_c]].map(([name,value])=>`<div class="gauge"><div class="gauge-ring" style="--percent:${typeof value==='number'?Math.max(0,Math.min(100,value)):0}"><span>${value===null?'N/A':num(value,0)+'%'}</span></div><small>${name}</small></div>`).join('');$('#hardware-detail').textContent=`RAM ${num(d.ram_used_gb)} / ${num(d.ram_total_gb)} GB · ${num(d.procs,0)} processes · ${d.gpu?.available?d.gpu.name+' · '+num(d.gpu.temperature_c)+'°C':'GPU unavailable'}`;$('#pc-time').textContent='Observed on this PC · '+new Date().toLocaleTimeString();setBadge('#pc-badge','OBSERVED','good');$('#connection').textContent='CONNECTED';$('#connection').className='connection good';}catch(e){setBadge('#pc-badge','UNAVAILABLE','warn');$('#connection').textContent='DEGRADED';$('#connection').className='connection';$('#top-cpu').textContent=$('#top-gpu').textContent=$('#top-ram').textContent='—';$('#pc-time').textContent='Telemetry refresh failed: '+e.message;}});}
async function quotes(){return once('quotes',async()=>{try{const d=await api('/api/markets');state.quotes=list(d);renderQuotes();}catch(e){$('#market-table').innerHTML='<tr><td colspan="4">Quotes unavailable: '+escape(e.message)+'</td></tr>';$('#impact-list').textContent='Market observations unavailable.';}});}
function instrument(q){return {'GC=F':'Gold futures','SI=F':'Silver futures','CL=F':'WTI futures','BZ=F':'Brent futures','^IXIC':'Nasdaq Composite'}[q.symbol]||q.name||q.symbol;}
function quoteRows(filter='all'){return state.quotes.filter(q=>filter==='all'||(filter==='crypto'?String(q.source).includes('CoinGecko'):filter==='forex'?String(q.symbol).endsWith('=X'):!String(q.source).includes('CoinGecko')&&!String(q.symbol).endsWith('=X'))).map(q=>{const observed=q.observed_at,stale=observed&&Date.now()-Date.parse(observed)>(q.stale_after_seconds||90)*1000;return `<tr><td>${escape(instrument(q))}<small>${escape(q.symbol)}</small></td><td>${num(q.price,5)}</td><td class="${typeof q.change==='number'?(q.change>=0?'positive':'negative'):''}">${num(q.change,2)}</td><td>${stale?'Delayed · ':''}${escape(age(observed||q.fetched_at))}<small>${escape(q.source)}${!observed?' · fetched time':''}</small></td></tr>`;}).join('')||'<tr><td colspan="4">No matching provider observations. Not a zero price.</td></tr>';}
function renderQuotes(){$('#market-table').innerHTML=quoteRows(state.market);$('#impact-list').innerHTML=state.quotes.slice(0,5).map(q=>`<div class="impact-item"><span>${escape(q.symbol)}</span><span class="${q.change>=0?'positive':'negative'}">${num(q.change,2)}%</span></div>`).join('')||'<p class="empty">No quotes returned.</p>';if($('#detail-quotes'))$('#detail-quotes').innerHTML=quoteRows(state.market);}
async function broker(){return once('broker',async()=>{try{const d=await api('/api/trading');state.broker=d;const a=d.account||{},verified=a.telemetry_verified===true&&a.available===true&&!['UNAVAILABLE','SIMULATION','UNKNOWN'].includes(d.data_mode);setBadge('#broker-badge',verified?'OBSERVED':'UNAVAILABLE',verified?'good':'warn');$('#broker-label').textContent=verified?`${a.broker||'Broker'} · ${a.server||''} · ${d.data_mode}`:'MQ3 connected · broker not verified';$('#broker-balance').textContent=verified?currency(a.balance):'Unavailable';$('#broker-equity').textContent=verified?currency(a.equity):'—';$('#broker-profit').textContent=verified?currency(a.profit):'—';$('#broker-note').textContent=verified?'Observed broker snapshot. Order controls are not enabled in this overview.':'No verified broker balance or equity. Historical/configured account data is not a live observation.';const positions=verified?list(d.positions):[];$('#positions-count').textContent=verified?String(positions.length):'—';$('#positions').replaceChildren();if(!verified||!positions.length){$('#positions').textContent=verified?'No open positions reported in this snapshot.':'Positions unavailable until broker telemetry is verified.';}positions.slice(0,8).forEach(p=>{const e=document.createElement('div');e.textContent=`${p.symbol||'Position'} · ${p.type??''} · ${num(p.volume,2)} lots · ${currency(p.profit)}`;$('#positions').append(e)});}catch(e){setBadge('#broker-badge','UNAVAILABLE','warn');$('#broker-balance').textContent='Unavailable';$('#broker-equity').textContent=$('#broker-profit').textContent='—';$('#positions').textContent='Broker refresh failed.';$('#broker-note').textContent=e.message;}});}
async function news(){return once('news',async()=>{try{const d=list(await api('/api/news'));state.news=d;$('#news-count').textContent=d.length;$('#news-list').replaceChildren();if(!d.length)$('#news-list').textContent='No news returned by connected sources.';d.slice(0,14).forEach(item=>{const a=document.createElement('a');a.className='news-item';const href=url(item.link);if(href){a.href=href;a.target='_blank';a.rel='noopener noreferrer';}const small=document.createElement('small');small.textContent=`${item.source||'Source unknown'} · ${age(item.published_at)}`;const title=document.createElement('span');title.textContent=item.title||'Untitled item';a.append(small,title);$('#news-list').append(a)});}catch(e){$('#news-list').textContent='News unavailable: '+e.message;}});}
async function services(){return once('services',async()=>{try{const d=await api('/api/platform/status');state.services=list(d.services);$('#source-list').innerHTML=state.services.map(s=>`<div class="source-row"><span class="status-dot ${s.available?'good':''}"></span><div>${escape(s.name.replaceAll('_',' '))}<small>${s.available?'HTTP '+s.http_status:'Unavailable'} · ${num(s.latency_ms,0)} ms</small></div></div>`).join('');$('#last-check').textContent='Services checked '+age(d.checked_at);if(state.page==='settings')renderServices();}catch(e){$('#source-list').textContent='Service check unavailable';$('#last-check').textContent='Service check failed';}});}
async function memoryStatus(){try{const d=await api('/api/memory/status');state.memory=d;$('#memory-summary').textContent=d.available?`${num(d.vectors,0)} vectors · ${num(d.documents,0)} documents reported by local SQLite. Browse original passages and sources.`:'Local memory unavailable.';}catch{$('#memory-summary').textContent='Local memory status unavailable.';}}
async function geo(){return once('geo',async()=>{try{state.geo=await api('/api/world/geojson');window.dispatchEvent(new CustomEvent('jarvis:geo',{detail:state.geo}));const rows=list(state.geo.features);$('#geo-status').textContent=`${rows.length} source-labelled locations · USGS observations / static chokepoints`; }catch{$('#geo-status').textContent='Overlay feed unavailable · static Earth basemap only';window.dispatchEvent(new CustomEvent('jarvis:geo',{detail:{features:[]}}));}});}
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('en-GB');$('#date').textContent=d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});}
function log(text){$('#terminal-output').textContent+=`\n${new Date().toLocaleTimeString()} ${text}\n`;const el=$('#terminal-output');if(el.textContent.length>40000)el.textContent=el.textContent.slice(-35000);el.scrollTop=el.scrollHeight;}
function stageCommand(command){$('#terminal-body').hidden=false;$('#terminal-toggle').setAttribute('aria-expanded','true');$('#terminal-input').value=command;$('#terminal-input').focus();toast('Command prepared. Review it before submitting.');}
function stopCapture(){state.capture?.getTracks().forEach(t=>t.stop());state.capture=null;clearInterval(state.screenTimer);state.screenTimer=null;const media=$('#capture-media');if(media)media.replaceChildren();if($('#capture-status'))$('#capture-status').textContent='OFF · no capture active';}
function cleanupPage(){stopCapture();if(state.recorder&&state.recorder.state!=='inactive'){state.recorder.stop();}state.recorder=null;document.querySelectorAll('.native-frame').forEach(frame=>frame.remove());}
function navigate(page){if(!names[page])return;cleanupPage();state.page=page;$$('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===page&&b.closest('nav'));if(b.closest('nav')){b.setAttribute('aria-label',names[b.dataset.page]);if(b.dataset.page===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}});$('#command-page').hidden=page!=='command';$('#detail-page').hidden=page==='command';$('#detail-title').textContent=names[page];history.replaceState(null,'','#'+page);if(page!=='command')renderPage(page);window.dispatchEvent(new Event('jarvis:layout'));}
function panel(title,body){return `<section class="panel"><div class="detail-intro"><h2>${title}</h2></div>${body}</section>`;}
function card(title,description,button='',attr=''){return `<article class="detail-card"><h3>${title}</h3><p>${description}</p>${button?`<button ${attr}>${button}</button>`:''}</article>`;}
function nativeView(key){if(!native[key])return;cleanupPage();state.page='native:'+key;$('#command-page').hidden=true;$('#detail-page').hidden=false;const [title,src]=native[key];$('#detail-title').textContent=title+' / Jarvis';$('#detail-content').innerHTML=panel(title,`<div class="native-note">Full native controls inside Jarvis. Provider configuration and source labels belong to this module; HTTP readiness alone does not verify every feature.</div><div class="detail-toolbar"><button data-page="command">Overview</button><button data-native="world">World Monitor</button><button data-native="gods">Gods Eye View</button><button data-native="mq3">MQ3</button></div><iframe class="native-frame" title="${title}" src="${src}" referrerpolicy="no-referrer" allow="fullscreen"></iframe>`);icons();record(title+' workspace opened');}
function renderPage(page){let html='';if(page==='world')html=panel('Global intelligence',`<div class="detail-intro">Keep the native layers, filters, source attribution and spatial controls of both installed engines within this workspace.</div><div class="detail-content detail-grid">${card('World Monitor','News, geospatial layers and global context. Available feeds depend on provider setup.','Open World Monitor','data-native="world"')}${card('Gods Eye View','Full 3D spatial engine and its original control surface.','Open 3D engine','data-native="gods"')}${card('Source-labelled overview','USGS observations and static maritime references on the integrated globe.','Return to globe','data-page="command"')}${card('Provider boundaries','Not every layer has a configured feed. Empty or unavailable does not mean nothing happened.')}</div>`);
else if(page==='trading')html=panel('MQ3 / broker workspace',`<div class="detail-intro">Verified balances and positions remain separate from research and configuration. No order buttons are enabled by this new overview.</div><div class="detail-content detail-grid">${card('Account telemetry',state.broker?.account?.telemetry_verified?'Observed snapshot available; use the overview for values.':'Current broker telemetry is unavailable. A configured account is not proof of connection.','Refresh broker snapshot','data-action="broker-refresh"')}${card('Complete MQ3 interface','Retain the original charts, account tools and strategy panels inside Jarvis. The backend’s execution restrictions still apply.','Open native MQ3','data-native="mq3"')}${card('Markets and research','Public quote observations with timestamp and provider, not fabricated trade signals.','Open research','data-page="markets"')}${card('Risk review','Firm rules, account binding, current prices and execution authorization must be verified separately. No risk-free trade promise.')}</div>`);
else if(page==='markets')html=panel('Market research desk',`<div class="detail-intro">Exchange / provider observations. Futures are labelled as futures, not spot FX. Source age is retained.</div><div class="detail-toolbar"><button data-action="quotes-refresh">Refresh observations</button><button data-native="mq3">MQ3 chart workspace</button><button data-native="world">World Monitor context</button></div><div class="quotes-detail"><div class="table-wrap"><table><thead><tr><th>Instrument</th><th>Price</th><th>Change %</th><th>Source age</th></tr></thead><tbody id="detail-quotes">${quoteRows()}</tbody></table></div></div>`);
else if(page==='chat')html=panel('Local intelligence & voice',`<div class="detail-intro">Chat with the assistant on the right. This new chat route uses only your installed Ollama model; it does not call paid cloud providers or run tools.</div><div class="detail-content detail-grid">${card('Text conversation','English or Roman Urdu. Provider and model are attached to each actual reply.','Focus assistant','data-action="focus-chat"')}${card('Voice input','Recording starts only after pressing Record and granting microphone access. Transcription is sent to the existing local speech endpoint.','Record / stop','data-action="record-voice"')}${card('Speech output','Read the last assistant reply through your browser’s configured speech voice.','Read last reply','data-action="speak"')}${card('Actions are separate','Use the terminal below for a request that should operate the PC. Generated text is never presented as execution evidence.')}</div><div id="voice-state" class="panel-foot">Microphone off</div>`);
else if(page==='pc'||page==='camera')html=panel(page==='pc'?'PC visual workspace':'Camera workspace',`<div class="detail-intro">Only explicit Start actions access your desktop or camera. Leaving this workspace stops this page’s capture session.</div><div class="detail-toolbar"><button data-action="start-screen">Start desktop view</button><button data-action="start-camera">Start this device’s camera</button><button data-action="stop-capture">Stop capture</button><button data-native="mobile">Remote controls</button></div><div class="panel-foot" id="capture-status">OFF · no capture active</div><div id="capture-media" class="permission-note">No camera, clipboard or screen has been requested by this page.</div><div class="detail-toolbar"><button data-command="show system status">Prepare system-status command</button><button data-native="terminal">Full terminal workspace</button></div>`);
else if(page==='mobile')html=panel('Android & remote control',`<div class="detail-intro">The mobile companion stays inside Jarvis. Phone connection and permission state are reported by the companion itself, not fabricated here.</div><div class="detail-content detail-grid">${card('Companion interface','Pair devices, use the existing mobile controls and inspect their actual connection status.','Open mobile workspace','data-native="mobile"')}${card('Independent Android app','Use the independently built Jarvis client based on the permitted original MIT route. APK and device installation require separate verification.')}${card('OpenDroid','Read the current device-adapter status before requesting actions.','Inspect device adapter','data-inspect="/api/mobile/opendroid/status"')}${card('Dimos','Inspect the installed spatial / device integration. Reported data is not certification of full readiness.','Inspect Dimos','data-inspect="/api/dimos/vitals"')}</div><div id="inspect-output"></div>`);
else if(page==='comms')html=panel('Communications hub',`<div class="detail-intro">WhatsApp connectivity, pairing and message tasks share the Jarvis workspace. This page never sends a message on load.</div><div class="detail-content detail-grid">${card('WhatsApp connection','Check whether the bridge is reachable and the account is actually linked.','Check connection','data-inspect="/api/whatsapp/status"')}${card('WhatsApp pairing','Display the existing bridge’s pairing QR in this workspace. Only scan it if you intend to link your account.','Show pairing QR','data-action="wa-qr"')}${card('Message drafting','Prepare a message in the terminal for review; no automatic broadcasts are enabled by this UI.','Prepare message draft','data-command="Help me draft a WhatsApp message; do not send it."')}${card('Discord & consensus','Inspect the consensus integration; channel sending requires a separate explicit action.','Inspect status','data-inspect="/api/consensus/status"')}</div><div id="inspect-output"></div>`);
else if(page==='memory')html=panel('Memory & knowledge',`<div class="detail-intro">${escape($('#memory-summary').textContent)} Search retrieves existing material; returned text is reference content, not instructions.</div><form id="memory-form" class="inline-search"><input id="memory-query" aria-label="Memory search" maxlength="500" placeholder="Search books, mission or saved knowledge…"><button>Search memory</button></form><div id="memory-results" aria-live="polite"></div><div class="detail-toolbar"><button data-inspect="/api/memory/status">Storage status</button><button data-inspect="/api/memory/graph">Knowledge relationships</button><button data-inspect="/api/memory/lessons">Stored lessons</button></div><div id="inspect-output"></div>`);
else if(page==='content')html=panel('Content studio',`<div class="detail-content detail-grid">${card('Animation library','Read the existing Manim / visual render catalogue. A listed template is not a completed render.','Inspect animation library','data-inspect="/api/visuals/animations"')}${card('Creative tasks','Prepare a generation request through the command router and inspect the returned artifact.','Prepare creative task','data-command="List available content creation tools and their current status."')}${card('Source & outputs','Generated output must be opened and checked before it is called complete. Existing assets and creative repo code remain preserved.')}${card('Coding workspace','Use the full terminal for repo work, tests and explicit commands.','Open terminal studio','data-native="terminal"')}</div><div id="inspect-output"></div>`);
else if(page==='agents')html=panel('Agent & tool workspace',`<div class="detail-intro">Installed integrations and provider claims are not the same as a tested run. Inspect status and task evidence before enabling work.</div><div class="detail-content detail-grid">${card('Local model','Inspect the actual local inference status.','Local AI status','data-inspect="/api/local_ai/status"')}${card('Research consensus','Inspect available council / reasoning components without dispatching a trading action.','Consensus status','data-inspect="/api/consensus/status"')}${card('Odysseus / DeerFlow / Vibe tools','Existing backend tool integrations remain available through the command router. Their complete native frontend migration is not claimed here.','Prepare capability inquiry','data-command="List installed agent and research tools with verified availability. Do not execute tasks."')}${card('Task evidence','Read runtime event observations.','Read event history','data-inspect="/api/jarvis/live_events"')}</div><div id="inspect-output"></div>`);
else if(page==='automation')html=panel('Automation & workflows',`<div class="detail-intro">Inspect configured workflows before scheduling or triggering anything. This new frontend does not activate unattended tasks.</div><div class="detail-content detail-grid">${card('n8n workflows','List the backend’s available workflow inventory. A failed connection is shown as an error.','Inspect workflows','data-inspect="/api/n8n/workflows"')}${card('Task preparation','Prepare a workflow request in the terminal; submission remains explicit.','Prepare task plan','data-command="Show a plan for my next automation task. Do not execute or schedule it."')}${card('Service supervision','HTTP readiness, availability and response age.','System workspace','data-page="settings"')}</div><div id="inspect-output"></div>`);
else if(page==='governance')html=panel('Governance & action boundaries',`<div class="detail-content detail-grid">${card('Read-only financial overview','No order submission, balance fabrication or automatic trade approval is implemented in this frontend.')}${card('Capture consent','Camera and desktop capture are off on load and stop when this page leaves the capture workspace.')}${card('Local assistant','The new assistant endpoint calls localhost Ollama only. Generated text does not execute tools.')}${card('Approvals & backend audit','Existing backend policies remain authoritative; stored gate claims require independent evidence. No system-wide safety certification is implied.','Inspect pending approvals','data-inspect="/api/approval/pending"')}</div><div id="inspect-output"></div>`);
else if(page==='settings')html=panel('System & integration status',`<div class="detail-intro">HTTP reachability is checked separately from functional readiness. Missing APIs, permissions and credentials still require setup.</div><div class="detail-toolbar"><button data-action="services-refresh">Refresh services</button><button data-inspect="/api/voice/status">Local speech status</button><button data-inspect="/api/memory/status">Memory status</button></div><div id="service-detail" class="readiness-list"></div><div id="inspect-output"></div>`);
$('#detail-content').innerHTML=html;icons();if(page==='settings')renderServices();if(page==='memory')$('#memory-form').addEventListener('submit',searchMemory);}
function renderServices(){const e=$('#service-detail');if(e)e.innerHTML=state.services.map(s=>`<div class="readiness-row"><div><b>${escape(s.name)}</b><small>${escape(s.url)} · checked ${escape(age(s.checked_at))}</small></div><span class="badge ${s.available?'good':'warn'}">${s.available?'HTTP '+s.http_status:'UNAVAILABLE'}</span></div>`).join('')||'<p>No service snapshot available.</p>';}
async function inspect(path){const target=$('#inspect-output');if(!target)return;target.textContent='Requesting '+path+'…';try{const d=await api(path);const pre=document.createElement('pre');pre.className='result-view';pre.textContent=JSON.stringify(d,null,2);target.replaceChildren(pre);record('Read '+path);}catch(e){target.textContent='Unavailable: '+e.message;}}
async function searchMemory(e){e.preventDefault();const query=$('#memory-query').value.trim();if(!query)return;const target=$('#memory-results');target.textContent='Searching local memory…';try{const d=await api('/api/memory/search?q='+encodeURIComponent(query));target.replaceChildren();const rows=Array.isArray(d)?d:(d.results||d.memories||d.matches);if(Array.isArray(rows)){if(!rows.length)target.textContent='No matching memories returned.';rows.slice(0,20).forEach(row=>{const el=document.createElement('article');el.className='memory-result';el.textContent=typeof row==='string'?row:JSON.stringify(row,null,2);target.append(el)});}else{const pre=document.createElement('pre');pre.className='result-view';pre.textContent=typeof d.text==='string'?d.text:JSON.stringify(d,null,2);target.append(pre)}record('Memory search completed');}catch(e){target.textContent='Memory search unavailable: '+e.message;}}
function addMessage(role,text,source=''){const el=document.createElement('div');el.className='message '+(role==='user'?'user-message':'assistant-message');if(source){const small=document.createElement('small');small.textContent=source;el.append(small)}el.append(document.createTextNode(text));$('#chat-messages').append(el);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;}
async function ask(prompt){if(state.busy||!prompt.trim())return;state.busy=true;$('#chat-send').disabled=true;$('#chat-status').textContent='Local model generating…';addMessage('user',prompt);try{const d=await api('/api/reference-ui/local-chat',{method:'POST',body:JSON.stringify({prompt,history:state.chat.slice(-8)}),timeout:95000});if(!d.ok||!d.text)throw Error(d.error||'No model response');addMessage('assistant',d.text,`${d.provider} · ${d.model} · text only`);state.chat.push({role:'user',content:prompt},{role:'assistant',content:d.text.slice(0,4000)});state.chat=state.chat.slice(-8);state.lastReply=d.text;setBadge('#ai-badge','RESPONDED','good');$('#chat-status').textContent='Local response · no tools executed';record('Local assistant returned a response');}catch(e){addMessage('assistant',e.message,'UNAVAILABLE');setBadge('#ai-badge','UNAVAILABLE','warn');$('#chat-status').textContent='Failed · no cloud fallback';}finally{state.busy=false;$('#chat-send').disabled=false;}}
function speak(){if(!state.lastReply)return toast('Ask Jarvis first; there is no reply to read yet.');if(!('speechSynthesis' in window))return toast('Browser speech synthesis unavailable.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(state.lastReply);speechSynthesis.speak(u);}
async function captureScreen(){stopCapture();const box=$('#capture-media');if(!box)return;box.replaceChildren();const img=document.createElement('img');img.className='capture-video';img.alt='Explicitly requested desktop capture';box.append(img);let loading=false;const refresh=()=>{if(loading||!['pc','camera'].includes(state.page)||document.hidden)return;loading=true;img.src='/api/screenshot?t='+Date.now();};img.onload=()=>{loading=false;if($('#capture-status'))$('#capture-status').textContent='DESKTOP VIEW ACTIVE · refreshed '+new Date().toLocaleTimeString();};img.onerror=()=>{loading=false;clearInterval(state.screenTimer);if($('#capture-status'))$('#capture-status').textContent='Desktop capture unavailable';};refresh();state.screenTimer=setInterval(refresh,2000);record('Desktop capture explicitly started');}
async function captureCamera(){stopCapture();const targetPage=state.page;try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});if(!['pc','camera'].includes(state.page)||state.page!==targetPage){stream.getTracks().forEach(t=>t.stop());return;}state.capture=stream;const video=document.createElement('video');video.className='capture-video';video.autoplay=true;video.muted=true;video.playsInline=true;video.srcObject=stream;$('#capture-media').replaceChildren(video);$('#capture-status').textContent='CAMERA ACTIVE · this browser device';record('Camera permission granted; stream started');}catch(e){if($('#capture-status'))$('#capture-status').textContent='Camera unavailable: '+e.message;}}
async function recordVoice(){if(state.recorder?.state==='recording'){state.recorder.stop();return;}if(!navigator.mediaDevices||!window.MediaRecorder)return toast('Audio recording is unavailable in this browser.');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(state.page!=='chat'){stream.getTracks().forEach(t=>t.stop());return;}const chunks=[],rec=new MediaRecorder(stream);state.recorder=rec;rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());if($('#voice-state'))$('#voice-state').textContent='Transcribing locally…';try{const blob=new Blob(chunks,{type:rec.mimeType});const response=await fetch('/api/voice/transcribe',{method:'POST',body:blob,signal:AbortSignal.timeout(60000)});const d=await response.json();if(!response.ok||d.ok===false||!d.text)throw Error(d.error||'No transcript returned');$('#chat-input').value=d.text;toast('Transcript ready. Review it and press Send.');}catch(e){toast('Transcription unavailable: '+e.message);}if($('#voice-state'))$('#voice-state').textContent='Microphone off';};rec.start();if($('#voice-state'))$('#voice-state').textContent='RECORDING · press Record / stop again to finish';setTimeout(()=>{if(rec.state==='recording')rec.stop();},20000);}catch(e){toast('Microphone unavailable: '+e.message);}}
const inspectAllow=new Set(['/api/mobile/opendroid/status','/api/dimos/vitals','/api/whatsapp/status','/api/consensus/status','/api/memory/status','/api/memory/graph','/api/memory/lessons','/api/visuals/animations','/api/local_ai/status','/api/jarvis/live_events','/api/n8n/workflows','/api/approval/pending','/api/voice/status']);
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page)navigate(b.dataset.page);if(b.dataset.native)nativeView(b.dataset.native);if(b.dataset.ask){$('#chat-input').value=b.dataset.ask;$('#chat-input').focus();}if(b.dataset.command)stageCommand(b.dataset.command);if(b.dataset.inspect&&inspectAllow.has(b.dataset.inspect))inspect(b.dataset.inspect);if(b.dataset.market){state.market=b.dataset.market;$$('[data-market]').forEach(x=>x.classList.toggle('active',x===b));renderQuotes();}switch(b.dataset.action){case 'broker-refresh':await broker();toast($('#broker-note').textContent);break;case 'quotes-refresh':await quotes();break;case 'services-refresh':await services();break;case 'focus-chat':$('#chat-input').focus();break;case 'start-screen':captureScreen();break;case 'start-camera':captureCamera();break;case 'stop-capture':stopCapture();record('Capture stopped');break;case 'record-voice':recordVoice();break;case 'speak':speak();break;case 'wa-qr':{const target=$('#inspect-output');const img=document.createElement('img');img.alt='WhatsApp bridge pairing QR';img.style.cssText='max-width:300px;width:100%;display:block;margin:20px';img.src='http://127.0.0.1:3200/qr';img.onerror=()=>target.textContent='Pairing QR unavailable. Check WhatsApp connection status.';target.replaceChildren(img);break;}}});
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const text=$('#chat-input').value.trim();if(!state.busy&&text){$('#chat-input').value='';ask(text);}});$('#header-chat').addEventListener('submit',e=>{e.preventDefault();const text=$('#header-prompt').value.trim();if(!state.busy&&text){$('#header-prompt').value='';ask(text);}});$('#speak-reply').addEventListener('click',speak);
$('#terminal-form').addEventListener('submit',e=>{e.preventDefault();const command=$('#terminal-input').value.trim();if(!command||state.terminalBusy)return;$('#command-review').textContent=command;$('#confirm-command').showModal();});$('#command-cancel').addEventListener('click',()=>$('#confirm-command').close());$('#command-confirm').addEventListener('click',async()=>{const command=$('#command-review').textContent;$('#confirm-command').close();if(state.terminalBusy)return;state.terminalBusy=true;$('#terminal-run').disabled=true;log('REQUEST > '+command);try{const d=await api('/api/terminal/exec',{method:'POST',body:JSON.stringify({command}),timeout:95000});log((d.ok?'RESULT':'NOT CONFIRMED')+' > '+(d.output||d.error||'No execution result returned'));if(d.metadata)log('Metadata: '+JSON.stringify(d.metadata));record(d.ok?'Command router returned a result':'Command needs attention / was not confirmed');$('#terminal-input').value='';}catch(e){log('ERROR > '+e.message+'; execution outcome may be unknown. Do not retry a consequential action blindly.');}finally{state.terminalBusy=false;$('#terminal-run').disabled=false;}});
$('#terminal-toggle').addEventListener('click',()=>{const body=$('#terminal-body');body.hidden=!body.hidden;$('#terminal-toggle').setAttribute('aria-expanded',String(!body.hidden));});$('#refresh-all').addEventListener('click',()=>{refresh();toast('Refreshing observations…');});
async function refresh(){await Promise.allSettled([pc(),quotes(),broker(),news(),services(),memoryStatus()]);}
window.addEventListener('hashchange',()=>{const page=location.hash.slice(1);if(names[page])navigate(page);});
window.addEventListener('pagehide',()=>{cleanupPage();window.speechSynthesis?.cancel();});document.addEventListener('visibilitychange',()=>{if(!document.hidden){pc();services();}});
clock();setInterval(clock,1000);navigate(names[location.hash.slice(1)]?location.hash.slice(1):'command');icons();refresh();geo();setInterval(()=>{if(!document.hidden)pc();},10000);setInterval(()=>{if(!document.hidden)refresh();},60000);setInterval(()=>{if(!document.hidden)geo();},120000);
import('./globe.js').then(({startGlobe})=>startGlobe($('#globe'),()=>state.geo)).catch(()=>{$('#globe-message').textContent='3D renderer unavailable. World Monitor and Gods Eye View remain accessible.';});
