import * as THREE from './vendor/three.module.min.js';

export function startGlobe(container, currentGeo) {
  const renderer = new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;
  renderer.domElement.setAttribute('aria-label','Interactive 3D Earth. Drag to rotate; zoom and arrow controls are available below.');
  renderer.domElement.setAttribute('role','img');container.prepend(renderer.domElement);
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.z=3.5;
  scene.add(new THREE.AmbientLight(0x8abaff,1.5));const sun=new THREE.DirectionalLight(0xb4e8ff,2.3);sun.position.set(-3,2,5);scene.add(sun);
  const world=new THREE.Group();scene.add(world);world.rotation.set(.15,-1.05,0);
  const material=new THREE.MeshPhongMaterial({color:0x779bb8,shininess:14,specular:0x123c67});
  const earth=new THREE.Mesh(new THREE.SphereGeometry(1,64,48),material);world.add(earth);
  new THREE.TextureLoader().load('/command-center-assets/vendor/earth.jpg',texture=>{texture.colorSpace=THREE.SRGBColorSpace;material.map=texture;material.color.set(0xc4d8ff);material.needsUpdate=true;document.getElementById('globe-message').hidden=true;render();},undefined,()=>{document.getElementById('globe-message').textContent='Earth texture unavailable · geometric globe';});
  const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.045,48,32),new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,blending:THREE.AdditiveBlending,depthWrite:false,uniforms:{},vertexShader:'varying vec3 n; varying vec3 v; void main(){vec4 p=modelViewMatrix*vec4(position,1.0);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n; varying vec3 v; void main(){float f=pow(1.0-abs(dot(n,v)),3.0);gl_FragColor=vec4(0.08,0.48,1.0,f*0.7);}'}));world.add(atmosphere);
  const coordinates=(lon,lat,r=1.014)=>{const phi=(90-lat)*Math.PI/180,theta=(lon+180)*Math.PI/180;return new THREE.Vector3(-r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta));};
  // Latitude rings are reference geometry, never represented as traffic tracks.
  for(const latitude of [-60,-30,0,30,60]){const points=[];for(let longitude=-180;longitude<=180;longitude+=3)points.push(coordinates(longitude,latitude,1.004));world.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x2395d5,transparent:true,opacity:.13})));}
  const stars=[];for(let i=0;i<180;i++){const a=i*2.39996323,y=1-2*(i+.5)/180,r=Math.sqrt(1-y*y);stars.push(Math.cos(a)*r*8,y*8,Math.sin(a)*r*8);}const starGeometry=new THREE.BufferGeometry();starGeometry.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));scene.add(new THREE.Points(starGeometry,new THREE.PointsMaterial({color:0x94d2f5,size:.013,transparent:true,opacity:.4})));
  const markers=new THREE.Group();world.add(markers);const layers={natural:true,waterways:true};let allFeatures=[],auto=false,drag=null,frame=0,last=0,visible=true;
  function setData(data){allFeatures=(data?.features||[]).filter(f=>f.geometry?.type==='Point'&&Array.isArray(f.geometry.coordinates)&&f.geometry.coordinates.slice(0,2).every(Number.isFinite));drawMarkers();}
  function drawMarkers(){while(markers.children.length){const item=markers.children[0];markers.remove(item);item.geometry.dispose();item.material.dispose();}for(const f of allFeatures){const layer=f.properties?.layer;if(!layers[layer])continue;const [lon,lat]=f.geometry.coordinates;if(Math.abs(lat)>90||Math.abs(lon)>180)continue;const marker=new THREE.Mesh(new THREE.SphereGeometry(layer==='natural'?.016:.012,8,6),new THREE.MeshBasicMaterial({color:layer==='natural'?0xffbf6a:0x5ae4ff}));marker.position.copy(coordinates(lon,lat,1.025));marker.userData=f.properties||{};markers.add(marker);}render();}
  function render(){if(!visible||document.hidden||container.offsetWidth===0)return;renderer.render(scene,camera);}
  function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();render();}
  const raycaster=new THREE.Raycaster();
  renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,rx:world.rotation.x,ry:world.rotation.y,moved:false};renderer.domElement.setPointerCapture(e.pointerId);});
  renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;world.rotation.y=drag.ry+dx*.006;world.rotation.x=Math.max(-1.4,Math.min(1.4,drag.rx+dy*.006));render();});
  renderer.domElement.addEventListener('pointerup',e=>{if(drag&&!drag.moved){const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects([earth,...markers.children],false)[0];const box=document.getElementById('marker-detail');if(hit&&hit.object!==earth){const p=hit.object.userData;box.replaceChildren();const heading=document.createElement('b');heading.textContent=p.title||p.name||'Location';const note=document.createElement('small');note.textContent=`${p.data_mode||'Reference'} · ${p.observed_at||'Static geographic reference'}`;const source=document.createElement('small');source.textContent=p.source||'Source not supplied';box.append(heading,note,source);box.hidden=false;}else box.hidden=true;}drag=null;});renderer.domElement.addEventListener('pointercancel',()=>drag=null);
  document.getElementById('globe-left').onclick=()=>{world.rotation.y-=.25;render();};document.getElementById('globe-right').onclick=()=>{world.rotation.y+=.25;render();};document.getElementById('globe-zoom').oninput=e=>{camera.position.z=Number(e.target.value);render();};document.getElementById('globe-reset').onclick=()=>{world.rotation.set(.15,-1.05,0);camera.position.z=3.5;document.getElementById('globe-zoom').value='3.5';document.getElementById('marker-detail').hidden=true;render();};
  document.getElementById('globe-home').onclick=()=>document.getElementById('globe-reset').click();
  function animate(t){frame=0;if(!auto||!visible||document.hidden)return;if(t-last>50){world.rotation.y+=.0015;render();last=t;}frame=requestAnimationFrame(animate);}
  document.getElementById('rotate-toggle').onclick=e=>{auto=!auto;e.currentTarget.setAttribute('aria-pressed',String(auto));if(auto&&!frame)frame=requestAnimationFrame(animate);};
  document.querySelectorAll('[data-layer]').forEach(button=>button.addEventListener('click',()=>{layers[button.dataset.layer]=!layers[button.dataset.layer];button.setAttribute('aria-pressed',String(layers[button.dataset.layer]));drawMarkers();}));
  new ResizeObserver(resize).observe(container);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible){resize();if(auto&&!frame)frame=requestAnimationFrame(animate);}}).observe(container);
  window.addEventListener('jarvis:geo',e=>setData(e.detail));window.addEventListener('jarvis:layout',resize);document.addEventListener('visibilitychange',()=>{if(!document.hidden){render();if(auto&&!frame)frame=requestAnimationFrame(animate);}});setData(currentGeo());resize();
  renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();document.getElementById('globe-message').hidden=false;document.getElementById('globe-message').textContent='3D context lost. Reload the page to recover.';});
}
